services:
  server:
    image: notzree/wikigraph_server:1.0
    env_file:
      - .env
    container_name: wikigraph_server
    ports:
      - 8080:8080
    build:
      context: ./
      dockerfile: ./server_infra/prod.Dockerfile
    environment:
      - DATABASE_URL=${SUPABASE_URL}
