version: '3.9'
services:
  postgres:
    env_file:
      - ./.env
    image: notzree/wikigraph_database:1.0
    platform: linux/arm64
    build:
      context: ./
      dockerfile: ./database_infra/Dockerfile
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
      - ./database_infra/:/docker-entrypoint-initdb.d
  server:
    image: notzree/wikigraph_server:2.0
    platform: linux/amd64
    env_file:
      - ./.env
    container_name: wikigraph_server
    stdin_open: true
    tty: true
    ports:
      - 3001:3001
    build:
      context: ./
      dockerfile: ./server_infra/Dockerfile
    depends_on:
      - postgres
volumes:
  postgres: