// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: proto/service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PathFinder_FindPath_FullMethodName = "/PathFinder/FindPath"
)

// PathFinderClient is the client API for PathFinder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PathFinderClient interface {
	FindPath(ctx context.Context, in *PathRequest, opts ...grpc.CallOption) (*PathResponse, error)
}

type pathFinderClient struct {
	cc grpc.ClientConnInterface
}

func NewPathFinderClient(cc grpc.ClientConnInterface) PathFinderClient {
	return &pathFinderClient{cc}
}

func (c *pathFinderClient) FindPath(ctx context.Context, in *PathRequest, opts ...grpc.CallOption) (*PathResponse, error) {
	out := new(PathResponse)
	err := c.cc.Invoke(ctx, PathFinder_FindPath_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PathFinderServer is the server API for PathFinder service.
// All implementations must embed UnimplementedPathFinderServer
// for forward compatibility
type PathFinderServer interface {
	FindPath(context.Context, *PathRequest) (*PathResponse, error)
	mustEmbedUnimplementedPathFinderServer()
}

// UnimplementedPathFinderServer must be embedded to have forward compatible implementations.
type UnimplementedPathFinderServer struct {
}

func (UnimplementedPathFinderServer) FindPath(context.Context, *PathRequest) (*PathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindPath not implemented")
}
func (UnimplementedPathFinderServer) mustEmbedUnimplementedPathFinderServer() {}

// UnsafePathFinderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PathFinderServer will
// result in compilation errors.
type UnsafePathFinderServer interface {
	mustEmbedUnimplementedPathFinderServer()
}

func RegisterPathFinderServer(s grpc.ServiceRegistrar, srv PathFinderServer) {
	s.RegisterService(&PathFinder_ServiceDesc, srv)
}

func _PathFinder_FindPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PathFinderServer).FindPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PathFinder_FindPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PathFinderServer).FindPath(ctx, req.(*PathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PathFinder_ServiceDesc is the grpc.ServiceDesc for PathFinder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PathFinder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PathFinder",
	HandlerType: (*PathFinderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindPath",
			Handler:    _PathFinder_FindPath_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}

const (
	AutoComplete_Complete_FullMethodName = "/AutoComplete/Complete"
)

// AutoCompleteClient is the client API for AutoComplete service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AutoCompleteClient interface {
	Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CompleteResponse, error)
}

type autoCompleteClient struct {
	cc grpc.ClientConnInterface
}

func NewAutoCompleteClient(cc grpc.ClientConnInterface) AutoCompleteClient {
	return &autoCompleteClient{cc}
}

func (c *autoCompleteClient) Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CompleteResponse, error) {
	out := new(CompleteResponse)
	err := c.cc.Invoke(ctx, AutoComplete_Complete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AutoCompleteServer is the server API for AutoComplete service.
// All implementations must embed UnimplementedAutoCompleteServer
// for forward compatibility
type AutoCompleteServer interface {
	Complete(context.Context, *CompleteRequest) (*CompleteResponse, error)
	mustEmbedUnimplementedAutoCompleteServer()
}

// UnimplementedAutoCompleteServer must be embedded to have forward compatible implementations.
type UnimplementedAutoCompleteServer struct {
}

func (UnimplementedAutoCompleteServer) Complete(context.Context, *CompleteRequest) (*CompleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Complete not implemented")
}
func (UnimplementedAutoCompleteServer) mustEmbedUnimplementedAutoCompleteServer() {}

// UnsafeAutoCompleteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AutoCompleteServer will
// result in compilation errors.
type UnsafeAutoCompleteServer interface {
	mustEmbedUnimplementedAutoCompleteServer()
}

func RegisterAutoCompleteServer(s grpc.ServiceRegistrar, srv AutoCompleteServer) {
	s.RegisterService(&AutoComplete_ServiceDesc, srv)
}

func _AutoComplete_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoCompleteServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutoComplete_Complete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoCompleteServer).Complete(ctx, req.(*CompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AutoComplete_ServiceDesc is the grpc.ServiceDesc for AutoComplete service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AutoComplete_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AutoComplete",
	HandlerType: (*AutoCompleteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Complete",
			Handler:    _AutoComplete_Complete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
